### ISSUE TITLE
Patent

### ISSUE THREAD

**Issue by ibmua** [ducha-aiki/numpy-sift#1]
I was just sifting through your repositories for curiosity purposes, but noticed this thing about a patent. US patents only work on US soil, it might matter to the README.md

**Comment by ducha-aiki** [comment]
Thank you for suggestion.
However, I don`t have enough qualification to evaluate if this is true or not, so I take safe side and leave it as is.
Second, I take all licence stuff from original implementation https://github.com/perdoch/hesaff, so if you convince Michal as well, I will re-think this :)

**Comment by ibmua** [comment]
https://www.stopfakes.gov/article?id=Is-My-US-Patent-Good-in-Other-Countries

**Comment by ducha-aiki** [comment]
Really, thank you, but I more appreciate some performance PRs :)
It does not really matter for personal use or scientific purposes. And in case of commercial use, I guess that people have lawyers and my readme.txt does not matter as well. 
Thing under my control is licence for code itself, which is the most permissive as possible.
